language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.8.16
  - DJANGO_VERSION=1.9.11
  - DJANGO_VERSION=1.10.3
# command to install dependencies
install: 
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: 
  - python runtests.py
