language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO_VERSION=1.11.20
# command to install dependencies
install: 
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: 
  - python runtests.py
